CREATE TABLE City (
    Zip VARCHAR2(10) PRIMARY KEY,
    CityName VARCHAR2(100) NOT NULL
);

CREATE TABLE Person (
    P_Tal VARCHAR2(20) PRIMARY KEY,
    FirstName VARCHAR2(100) NOT NULL,
    LastName VARCHAR2(100) NOT NULL,
    Zip VARCHAR2(10) NOT NULL,
    CONSTRAINT fk_person_city
        FOREIGN KEY (Zip) REFERENCES City(Zip)
);

CREATE TABLE Customer (
    P_Tal VARCHAR2(20) PRIMARY KEY,
    CommentText VARCHAR2(255),
    CONSTRAINT fk_customer_person
        FOREIGN KEY (P_Tal) REFERENCES Person(P_Tal)
);

CREATE TABLE Employee (
    P_Tal VARCHAR2(20) PRIMARY KEY,
    Salary NUMBER(10,2) NOT NULL,
    StartDate DATE NOT NULL,
    CONSTRAINT fk_employee_person
        FOREIGN KEY (P_Tal) REFERENCES Person(P_Tal)
);

CREATE TABLE AccountType (
    AccountTypeId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TypeName VARCHAR2(100) NOT NULL UNIQUE,
    CreditInterest NUMBER(5,2) NOT NULL,
    DebitInterest NUMBER(5,2) NOT NULL,
    OverdraftInterest NUMBER(5,2) NOT NULL
);

CREATE TABLE TransactionType (
    TransactionTypeId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TypeName VARCHAR2(100) NOT NULL UNIQUE
);

CREATE TABLE RelationshipType (
    RelationshipTypeId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TypeName VARCHAR2(100) NOT NULL UNIQUE
);

CREATE TABLE Account (
    AccountNumber VARCHAR2(30) PRIMARY KEY,
    Balance NUMBER(12,2) DEFAULT 0 NOT NULL,
    AllowedOverdraft NUMBER(12,2) DEFAULT 0 NOT NULL,
    CreatedDate DATE NOT NULL,
    CustomerPTal VARCHAR2(20) NOT NULL,
    AccountTypeId NUMBER NOT NULL,
    CONSTRAINT fk_account_customer
        FOREIGN KEY (CustomerPTal) REFERENCES Customer(P_Tal),
    CONSTRAINT fk_account_type
        FOREIGN KEY (AccountTypeId) REFERENCES AccountType(AccountTypeId)
);

CREATE TABLE AccountAccess (
    AccountAccessId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PersonPTal VARCHAR2(20) NOT NULL,
    AccountNumber VARCHAR2(30) NOT NULL,
    CanView NUMBER(1) DEFAULT 0 NOT NULL,
    CanTransfer NUMBER(1) DEFAULT 0 NOT NULL,
    StartDate DATE NOT NULL,
    EndDate DATE,
    CONSTRAINT fk_accountaccess_person
        FOREIGN KEY (PersonPTal) REFERENCES Person(P_Tal),
    CONSTRAINT fk_accountaccess_account
        FOREIGN KEY (AccountNumber) REFERENCES Account(AccountNumber)
);

CREATE TABLE FamilyRelation (
    FamilyRelationId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Person1PTal VARCHAR2(20) NOT NULL,
    Person2PTal VARCHAR2(20) NOT NULL,
    StartDate DATE NOT NULL,
    EndDate DATE,
    RelationshipTypeId NUMBER NOT NULL,
    CONSTRAINT fk_family_person1
        FOREIGN KEY (Person1PTal) REFERENCES Person(P_Tal),
    CONSTRAINT fk_family_person2
        FOREIGN KEY (Person2PTal) REFERENCES Person(P_Tal),
    CONSTRAINT fk_family_type
        FOREIGN KEY (RelationshipTypeId) REFERENCES RelationshipType(RelationshipTypeId)
);

CREATE TABLE DraftTransfer (
    DraftTransferId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Amount NUMBER(12,2) NOT NULL,
    TransferDate DATE NOT NULL,
    Status VARCHAR2(20) NOT NULL,
    FromAccountNumber VARCHAR2(30) NOT NULL,
    ToAccountNumber VARCHAR2(30) NOT NULL,
    CONSTRAINT fk_draft_from
        FOREIGN KEY (FromAccountNumber) REFERENCES Account(AccountNumber),
    CONSTRAINT fk_draft_to
        FOREIGN KEY (ToAccountNumber) REFERENCES Account(AccountNumber)
);

CREATE TABLE TransactionRecord (
    TransactionId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TransactionDate DATE NOT NULL,
    Amount NUMBER(12,2) NOT NULL,
    Description VARCHAR2(255),
    AccountNumber VARCHAR2(30) NOT NULL,
    TransactionTypeId NUMBER NOT NULL,
    CONSTRAINT fk_transaction_account
        FOREIGN KEY (AccountNumber) REFERENCES Account(AccountNumber),
    CONSTRAINT fk_transaction_type
        FOREIGN KEY (TransactionTypeId) REFERENCES TransactionType(TransactionTypeId)
);
